apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "bundle.fullname" . }}-{{ .Values.apiRegistrationJobName }}-config
data:
  SYSTEM_URL	: {{ .Values.system_url | quote }}
  APPLICATION_NAME: {{ .Values.application_name | quote }}
  PROVIDER_NAME: Github
  PRODUCT_NAME: Github
  APP_KIND: rest-with-apikey
  API_DESCRIPTION: "APIs for Github.com"  
