apiVersion: v1
data:
  EVENT_SIGN_SECRET: {{ .Values.secret }}
kind: Secret
metadata:
  creationTimestamp: null
  name: {{ template "bundle.fullname" . }}-{{ .Values.apiRegistrationJobName }}-github-event-gw
  namespace: {{ .Values.namespace }}
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ template "bundle.fullname" . }}
    component: {{ template "bundle.fullname" . }}-{{ .Values.apiRegistrationJobName }}
    kind: event-gw
  name: {{ template "bundle.fullname" . }}-{{ .Values.apiRegistrationJobName }}-github-event-gw
  namespace: kyma-integration
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ template "bundle.fullname" . }}
    component: {{ template "bundle.fullname" . }}-{{ .Values.apiRegistrationJobName }}
    kind: event-gw
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: gateway.kyma-project.io/v1alpha2
kind: Api
metadata:
  name: {{ template "bundle.fullname" . }}-{{ .Values.apiRegistrationJobName }}-github-event-gw
  namespace: kyma-integration
spec:
  authentication: []
  hostname: github-event-gw.{{ .Values.cluster_domain }}
  service:
    name: github-event-gw
    port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{ template "bundle.fullname" . }}
    component: {{ template "bundle.fullname" . }}-{{ .Values.apiRegistrationJobName }}
    kind: event-gw
  name: {{ template "bundle.fullname" . }}-{{ .Values.apiRegistrationJobName }}-github-event-gw
  namespace: kyma-integration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "bundle.fullname" . }}
      component: {{ template "bundle.fullname" . }}-{{ .Values.apiRegistrationJobName }}
      kind: event-gw
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ template "bundle.fullname" . }}
        component: {{ template "bundle.fullname" . }}-{{ .Values.apiRegistrationJobName }}
        kind: event-gw
    spec:
      containers:
      - image: gabbi/github-event-gw:0.0.1
        name: github-event-gw
        resources: {}
        ports:
          - containerPort: 8080
            protocol: TCP
        envFrom:
          - secretRef:
              name: {{ template "bundle.fullname" . }}-{{ .Values.apiRegistrationJobName }}-github-event-gw
              optional: false
        args:
          - --verbose=false
          - --basic-auth-enabled=true
          - --app-name={{ .Values.application_name | quote }}
          - --event-publish-url=http://event-publish-service.kyma-system.svc.cluster.local:8080/v1/events
          - --secret-key=$(EVENT_SIGN_SECRET)
status: {}
