name: docusign-connector
version: 0.0.1
description: "Enables the preview integration of DocuSign. It is not recommended for production scenarios."
id: 7b05b250-aea5-42c8-9ad0-a86c5ef593ed
displayName: "[Preview] DocuSign - Connector"
tags: preview,docusign,connector
labels: 
  preview: "true"
providerDisplayName: DocuSign
longDescription: "Integrates DocuSign Events(webhooks) and REST APIs. It is not recommended for production use."
bindable: false
provisionOnlyOnce: true
